{
	_synapse: Synapse;
	_signer: NonceManager;
	provider: [Object ...],
      signer
	: [Object ...],
      getAddress: [AsyncFunction: getAddress],
      connect: [Function: connect],
      getNonce: [AsyncFunction: getNonce],
      increment: [Function: increment],
      reset: [Function: reset],
      sendTransaction: [AsyncFunction: sendTransaction],
      signTransaction: [Function: signTransaction],
      signMessage: [Function: signMessage],
      signTypedData: [Function: signTypedData],
      populateCall: [AsyncFunction: populateCall],
      populateTransaction: [AsyncFunction: populateTransaction],
      populateAuthorization: [AsyncFunction: populateAuthorization],
      estimateGas: [AsyncFunction: estimateGas],
      call: [AsyncFunction: call],
      resolveName: [AsyncFunction: resolveName],
      authorize: [Function: authorize],
	,
    _network: "calibration",
    _withCDN: true,
    _payments: PaymentsService
	_provider: [Object ...],
      _signer
	: [Object ...],
      _paymentsAddress: "0x09a0fDc2723fAd1A7b8e3e00eE5DF73841df55a0",
      _usdfcAddress: "0xb3042734b608a1B16e9e86B374A3f3e389B4cDf0",
      _disableNonceManager: false,
      _usdfcContract: null,
      _paymentsContract: null,
      _getUsdfcContract: [Function: _getUsdfcContract],
      _getPaymentsContract: [Function: _getPaymentsContract],
      _getPermitSignature: [AsyncFunction: _getPermitSignature],
      balance: [AsyncFunction: balance],
      accountInfo: [AsyncFunction: accountInfo],
      walletBalance: [AsyncFunction: walletBalance],
      decimals: [Function: decimals],
      allowance: [AsyncFunction: allowance],
      approve: [AsyncFunction: approve],
      approveService: [AsyncFunction: approveService],
      revokeService: [AsyncFunction: revokeService],
      serviceApproval: [AsyncFunction: serviceApproval],
      deposit: [AsyncFunction: deposit],
      depositWithPermit: [AsyncFunction: depositWithPermit],
      depositWithPermitAndApproveOperator: [AsyncFunction: depositWithPermitAndApproveOperator],
      withdraw: [AsyncFunction: withdraw],
      settle: [AsyncFunction: settle],
      getSettlementAmounts: [AsyncFunction: getSettlementAmounts],
      settleTerminatedRail: [AsyncFunction: settleTerminatedRail],
      getRail: [AsyncFunction: getRail],
      settleAuto: [AsyncFunction: settleAuto],
      getRailsAsPayer: [AsyncFunction: getRailsAsPayer],
      getRailsAsPayee: [AsyncFunction: getRailsAsPayee],
	,
    _provider: WebSocketProvider
	websocket: [Getter], _write;
	: [AsyncFunction: _write],
      destroy: [AsyncFunction: destroy],
      _getSubscriber: [Function: _getSubscriber],
      _register: [Function: _register],
      _send: [AsyncFunction: _send],
      _processMessage: [AsyncFunction: _processMessage],
      _getOption: [Function: _getOption],
      _network: [Getter],
      _perform: [AsyncFunction: _perform],
      _detectNetwork: [AsyncFunction: _detectNetwork],
      _start: [Function: _start],
      _waitUntilReady: [AsyncFunction: _waitUntilReady],
      ready: [Getter],
      getRpcTransaction: [Function: getRpcTransaction],
      getRpcRequest: [Function: getRpcRequest],
      getRpcError: [Function: getRpcError],
      send: [Function: send],
      getSigner: [AsyncFunction: getSigner],
      listAccounts: [AsyncFunction: listAccounts],
      pollingInterval: [Getter],
      provider: [Getter],
      plugins: [Getter],
      attachPlugin: [Function: attachPlugin],
      getPlugin: [Function: getPlugin],
      disableCcipRead: [Getter/Setter],
      ccipReadFetch: [AsyncFunction: ccipReadFetch],
      _wrapBlock: [Function: _wrapBlock],
      _wrapLog: [Function: _wrapLog],
      _wrapTransactionReceipt: [Function: _wrapTransactionReceipt],
      _wrapTransactionResponse: [Function: _wrapTransactionResponse],
      getBlockNumber: [AsyncFunction: getBlockNumber],
      _getAddress: [Function: _getAddress],
      _getBlockTag: [Function: _getBlockTag],
      _getFilter: [Function: _getFilter],
      _getTransactionRequest: [Function: _getTransactionRequest],
      getNetwork: [AsyncFunction: getNetwork],
      getFeeData: [AsyncFunction: getFeeData],
      estimateGas: [AsyncFunction: estimateGas],
      call: [AsyncFunction: call],
      getBalance: [AsyncFunction: getBalance],
      getTransactionCount: [AsyncFunction: getTransactionCount],
      getCode: [AsyncFunction: getCode],
      getStorage: [AsyncFunction: getStorage],
      broadcastTransaction: [AsyncFunction: broadcastTransaction],
      getBlock: [AsyncFunction: getBlock],
      getTransaction: [AsyncFunction: getTransaction],
      getTransactionReceipt: [AsyncFunction: getTransactionReceipt],
      getTransactionResult: [AsyncFunction: getTransactionResult],
      getLogs: [AsyncFunction: getLogs],
      _getProvider: [Function: _getProvider],
      getResolver: [AsyncFunction: getResolver],
      getAvatar: [AsyncFunction: getAvatar],
      resolveName: [AsyncFunction: resolveName],
      lookupAddress: [AsyncFunction: lookupAddress],
      waitForTransaction: [AsyncFunction: waitForTransaction],
      waitForBlock: [AsyncFunction: waitForBlock],
      _clearTimeout: [Function: _clearTimeout],
      _setTimeout: [Function: _setTimeout],
      _forEachSubscriber: [Function: _forEachSubscriber],
      _recoverSubscriber: [Function: _recoverSubscriber],
      on: [AsyncFunction: on],
      once: [AsyncFunction: once],
      emit: [AsyncFunction: emit],
      listenerCount: [AsyncFunction: listenerCount],
      listeners: [AsyncFunction: listeners],
      off: [AsyncFunction: off],
      removeAllListeners: [AsyncFunction: removeAllListeners],
      addListener: [AsyncFunction: addListener],
      removeListener: [AsyncFunction: removeListener],
      destroyed: [Getter],
      paused: [Getter/Setter],
      pause: [Function: pause],
      resume: [Function: resume],
	,
    _warmStorageAddress: "0x02925630df557F957f70E112bA06e50965417CA0",
    _warmStorageService: WarmStorageService
	_provider: [Object ...],
      _warmStorageAddress
	: "0x02925630df557F957f70E112bA06e50965417CA0",
      _warmStorageContract: null,
      _warmStorageViewContract: [Object ...],
      _pdpVerifier: [Object ...],
      _addresses: [Object ...],
      getPDPVerifierAddress: [Function: getPDPVerifierAddress],
      getPaymentsAddress: [Function: getPaymentsAddress],
      getUSDFCTokenAddress: [Function: getUSDFCTokenAddress],
      getViewContractAddress: [Function: getViewContractAddress],
      getServiceProviderRegistryAddress: [Function: getServiceProviderRegistryAddress],
      getSessionKeyRegistryAddress: [Function: getSessionKeyRegistryAddress],
      getProvider: [Function: getProvider],
      _getWarmStorageContract: [Function: _getWarmStorageContract],
      _getWarmStorageViewContract: [Function: _getWarmStorageViewContract],
      _getPDPVerifier: [Function: _getPDPVerifier],
      getDataSet: [AsyncFunction: getDataSet],
      getClientDataSets: [AsyncFunction: getClientDataSets],
      getClientDataSetsWithDetails: [AsyncFunction: getClientDataSetsWithDetails],
      validateDataSet: [AsyncFunction: validateDataSet],
      verifyDataSetCreation: [AsyncFunction: verifyDataSetCreation],
      getComprehensiveDataSetStatus: [AsyncFunction: getComprehensiveDataSetStatus],
      waitForDataSetCreationWithStatus: [AsyncFunction: waitForDataSetCreationWithStatus],
      getDataSetMetadata: [AsyncFunction: getDataSetMetadata],
      getDataSetMetadataByKey: [AsyncFunction: getDataSetMetadataByKey],
      getPieceMetadata: [AsyncFunction: getPieceMetadata],
      getPieceMetadataByKey: [AsyncFunction: getPieceMetadataByKey],
      getServicePrice: [AsyncFunction: getServicePrice],
      calculateStorageCost: [AsyncFunction: calculateStorageCost],
      checkAllowanceForStorage: [AsyncFunction: checkAllowanceForStorage],
      prepareStorageUpload: [AsyncFunction: prepareStorageUpload],
      terminateDataSet: [AsyncFunction: terminateDataSet],
      addApprovedProvider: [AsyncFunction: addApprovedProvider],
      removeApprovedProvider: [AsyncFunction: removeApprovedProvider],
      getApprovedProviderIds: [AsyncFunction: getApprovedProviderIds],
      isProviderIdApproved: [AsyncFunction: isProviderIdApproved],
      getOwner: [AsyncFunction: getOwner],
      isOwner: [AsyncFunction: isOwner],
      getMaxProvingPeriod: [AsyncFunction: getMaxProvingPeriod],
      getChallengeWindow: [AsyncFunction: getChallengeWindow],
      topUpCDNPaymentRails: [AsyncFunction: topUpCDNPaymentRails],
	,
    _pieceRetriever: FilBeamRetriever
	baseRetriever: [Object ...],
      network
	: "calibration",
      hostname: [Function: hostname],
      fetchPiece: [AsyncFunction: fetchPiece],
	,
    _storageManager: StorageManager
	_synapse: [Circular], _warmStorageService;
	: [Object ...],
      _pieceRetriever: [Object ...],
      _withCDN: true,
      _dev: false,
      _withIpni: undefined,
      _defaultContext: [Circular],
      upload: [AsyncFunction: upload],
      download: [AsyncFunction: download],
      preflightUpload: [AsyncFunction: preflightUpload],
      createContext: [AsyncFunction: createContext],
      getDefaultContext: [AsyncFunction: getDefaultContext],
      findDataSets: [AsyncFunction: findDataSets],
      terminateDataSet: [AsyncFunction: terminateDataSet],
      getStorageInfo: [AsyncFunction: getStorageInfo],
	,
    _session: null,
    getNetwork: [Function: getNetwork],
    telemetry: [Getter],
    getSigner: [Function: getSigner],
    getClient: [Function: getClient],
    createSessionKey: [Function: createSessionKey],
    setSession: [Function: setSession],
    getProvider: [Function: getProvider],
    getChainId: [Function: getChainId],
    getWarmStorageAddress: [Function: getWarmStorageAddress],
    getPaymentsAddress: [Function: getPaymentsAddress],
    getPDPVerifierAddress: [Function: getPDPVerifierAddress],
    payments: [Getter],
    storage: [Getter],
    createStorage: [AsyncFunction: createStorage],
    download: [AsyncFunction: download],
    getProviderInfo: [AsyncFunction: getProviderInfo],
    getStorageInfo: [AsyncFunction: getStorageInfo],
	,
  _provider:
	id: 5, serviceProvider;
	: "0xB709A785c765d7d3F7d94dbA367DA6a611D7972b",
    payee: "0xB709A785c765d7d3F7d94dbA367DA6a611D7972b",
    name: "Mongo2Stor",
    description: "CA, US",
    active: true,
    products:
	PDP: [Object ...],
	,
	,
  _pdpServer: PDPServer
	_serviceURL: "http://warp.lotus.dedyn.io:9555", _authHelper;
	: PDPAuthHelper
	signer: [Object ...],
      domain
	: [Object ...],
      WITH_CDN_METADATA: [Object ...],
      getUnderlyingSigner: [Function: getUnderlyingSigner],
      isMetaMaskSigner: [AsyncFunction: isMetaMaskSigner],
      signWithMetaMask: [AsyncFunction: signWithMetaMask],
      signCreateDataSet: [AsyncFunction: signCreateDataSet],
      signAddPieces: [AsyncFunction: signAddPieces],
      signSchedulePieceRemovals: [AsyncFunction: signSchedulePieceRemovals],
      signDeleteDataSet: [AsyncFunction: signDeleteDataSet],
      getSignerAddress: [AsyncFunction: getSignerAddress],
	,
    createDataSet: [AsyncFunction: createDataSet],
    createAndAddPieces: [AsyncFunction: createAndAddPieces],
    addPieces: [AsyncFunction: addPieces],
    getDataSetCreationStatus: [AsyncFunction: getDataSetCreationStatus],
    getPieceAdditionStatus: [AsyncFunction: getPieceAdditionStatus],
    findPiece: [AsyncFunction: findPiece],
    getPieceStatus: [AsyncFunction: getPieceStatus],
    uploadPiece: [AsyncFunction: uploadPiece],
    downloadPiece: [AsyncFunction: downloadPiece],
    getDataSet: [AsyncFunction: getDataSet],
    deletePiece: [AsyncFunction: deletePiece],
    _encodeDataSetCreateData: [Function: _encodeDataSetCreateData],
    _encodeAddPiecesExtraData: [Function: _encodeAddPiecesExtraData],
    ping: [AsyncFunction: ping],
    getServiceURL: [Function: getServiceURL],
    getAuthHelper: [Function: getAuthHelper],
	,
  _warmStorageService: WarmStorageService
	_provider: WebSocketProvider;
	websocket: [Getter], _write;
	: [AsyncFunction: _write],
      destroy: [AsyncFunction: destroy],
      _getSubscriber: [Function: _getSubscriber],
      _register: [Function: _register],
      _send: [AsyncFunction: _send],
      _processMessage: [AsyncFunction: _processMessage],
      _getOption: [Function: _getOption],
      _network: [Getter],
      _perform: [AsyncFunction: _perform],
      _detectNetwork: [AsyncFunction: _detectNetwork],
      _start: [Function: _start],
      _waitUntilReady: [AsyncFunction: _waitUntilReady],
      ready: [Getter],
      getRpcTransaction: [Function: getRpcTransaction],
      getRpcRequest: [Function: getRpcRequest],
      getRpcError: [Function: getRpcError],
      send: [Function: send],
      getSigner: [AsyncFunction: getSigner],
      listAccounts: [AsyncFunction: listAccounts],
      pollingInterval: [Getter],
      provider: [Getter],
      plugins: [Getter],
      attachPlugin: [Function: attachPlugin],
      getPlugin: [Function: getPlugin],
      disableCcipRead: [Getter/Setter],
      ccipReadFetch: [AsyncFunction: ccipReadFetch],
      _wrapBlock: [Function: _wrapBlock],
      _wrapLog: [Function: _wrapLog],
      _wrapTransactionReceipt: [Function: _wrapTransactionReceipt],
      _wrapTransactionResponse: [Function: _wrapTransactionResponse],
      getBlockNumber: [AsyncFunction: getBlockNumber],
      _getAddress: [Function: _getAddress],
      _getBlockTag: [Function: _getBlockTag],
      _getFilter: [Function: _getFilter],
      _getTransactionRequest: [Function: _getTransactionRequest],
      getNetwork: [AsyncFunction: getNetwork],
      getFeeData: [AsyncFunction: getFeeData],
      estimateGas: [AsyncFunction: estimateGas],
      call: [AsyncFunction: call],
      getBalance: [AsyncFunction: getBalance],
      getTransactionCount: [AsyncFunction: getTransactionCount],
      getCode: [AsyncFunction: getCode],
      getStorage: [AsyncFunction: getStorage],
      broadcastTransaction: [AsyncFunction: broadcastTransaction],
      getBlock: [AsyncFunction: getBlock],
      getTransaction: [AsyncFunction: getTransaction],
      getTransactionReceipt: [AsyncFunction: getTransactionReceipt],
      getTransactionResult: [AsyncFunction: getTransactionResult],
      getLogs: [AsyncFunction: getLogs],
      _getProvider: [Function: _getProvider],
      getResolver: [AsyncFunction: getResolver],
      getAvatar: [AsyncFunction: getAvatar],
      resolveName: [AsyncFunction: resolveName],
      lookupAddress: [AsyncFunction: lookupAddress],
      waitForTransaction: [AsyncFunction: waitForTransaction],
      waitForBlock: [AsyncFunction: waitForBlock],
      _clearTimeout: [Function: _clearTimeout],
      _setTimeout: [Function: _setTimeout],
      _forEachSubscriber: [Function: _forEachSubscriber],
      _recoverSubscriber: [Function: _recoverSubscriber],
      on: [AsyncFunction: on],
      once: [AsyncFunction: once],
      emit: [AsyncFunction: emit],
      listenerCount: [AsyncFunction: listenerCount],
      listeners: [AsyncFunction: listeners],
      off: [AsyncFunction: off],
      removeAllListeners: [AsyncFunction: removeAllListeners],
      addListener: [AsyncFunction: addListener],
      removeListener: [AsyncFunction: removeListener],
      destroyed: [Getter],
      paused: [Getter/Setter],
      pause: [Function: pause],
      resume: [Function: resume],
	,
    _warmStorageAddress: "0x02925630df557F957f70E112bA06e50965417CA0",
    _warmStorageContract: null,
    _warmStorageViewContract: Contract
	target: "0xA5D87b04086B1d591026cCE10255351B5AA4689B", interface;
	: [Object ...],
      runner: [Object ...],
      filters: [Object ...],
      [Symbol(_ethersInternal_contract)]: [Object ...],
      fallback: null,
      connect: [Function: connect],
      attach: [Function: attach],
      getAddress: [AsyncFunction: getAddress],
      getDeployedCode: [AsyncFunction: getDeployedCode],
      waitForDeployment: [AsyncFunction: waitForDeployment],
      deploymentTransaction: [Function: deploymentTransaction],
      getFunction: [Function: getFunction],
      getEvent: [Function: getEvent],
      queryTransaction: [AsyncFunction: queryTransaction],
      queryFilter: [AsyncFunction: queryFilter],
      on: [AsyncFunction: on],
      once: [AsyncFunction: once],
      emit: [AsyncFunction: emit],
      listenerCount: [AsyncFunction: listenerCount],
      listeners: [AsyncFunction: listeners],
      off: [AsyncFunction: off],
      removeAllListeners: [AsyncFunction: removeAllListeners],
      addListener: [AsyncFunction: addListener],
      removeListener: [AsyncFunction: removeListener],
	,
    _pdpVerifier: PDPVerifier
	_provider: [Object ...],
      _contractAddress
	: "0x85e366Cf9DD2c0aE37E963d9556F5f4718d6417C",
      _contract: [Object ...],
      dataSetLive: [AsyncFunction: dataSetLive],
      getNextPieceId: [AsyncFunction: getNextPieceId],
      getDataSetListener: [AsyncFunction: getDataSetListener],
      getDataSetStorageProvider: [AsyncFunction: getDataSetStorageProvider],
      getDataSetLeafCount: [AsyncFunction: getDataSetLeafCount],
      extractDataSetIdFromReceipt: [Function: extractDataSetIdFromReceipt],
      getActivePieces: [AsyncFunction: getActivePieces],
      getContractAddress: [Function: getContractAddress],
	,
    _addresses:
	pdpVerifier: "0x85e366Cf9DD2c0aE37E963d9556F5f4718d6417C", payments;
	: "0x09a0fDc2723fAd1A7b8e3e00eE5DF73841df55a0",
      usdfcToken: "0xb3042734b608a1B16e9e86B374A3f3e389B4cDf0",
      filBeamBeneficiary: "0x1D60d2F5960Af6341e842C539985FA297E10d6eA",
      viewContract: "0xA5D87b04086B1d591026cCE10255351B5AA4689B",
      serviceProviderRegistry: "0x839e5c9988e4e9977d40708d0094103c0839Ac9D",
      sessionKeyRegistry: "0x97Dd879F5a97A8c761B94746d7F5cfF50AAd4452",
	,
    getPDPVerifierAddress: [Function: getPDPVerifierAddress],
    getPaymentsAddress: [Function: getPaymentsAddress],
    getUSDFCTokenAddress: [Function: getUSDFCTokenAddress],
    getViewContractAddress: [Function: getViewContractAddress],
    getServiceProviderRegistryAddress: [Function: getServiceProviderRegistryAddress],
    getSessionKeyRegistryAddress: [Function: getSessionKeyRegistryAddress],
    getProvider: [Function: getProvider],
    _getWarmStorageContract: [Function: _getWarmStorageContract],
    _getWarmStorageViewContract: [Function: _getWarmStorageViewContract],
    _getPDPVerifier: [Function: _getPDPVerifier],
    getDataSet: [AsyncFunction: getDataSet],
    getClientDataSets: [AsyncFunction: getClientDataSets],
    getClientDataSetsWithDetails: [AsyncFunction: getClientDataSetsWithDetails],
    validateDataSet: [AsyncFunction: validateDataSet],
    verifyDataSetCreation: [AsyncFunction: verifyDataSetCreation],
    getComprehensiveDataSetStatus: [AsyncFunction: getComprehensiveDataSetStatus],
    waitForDataSetCreationWithStatus: [AsyncFunction: waitForDataSetCreationWithStatus],
    getDataSetMetadata: [AsyncFunction: getDataSetMetadata],
    getDataSetMetadataByKey: [AsyncFunction: getDataSetMetadataByKey],
    getPieceMetadata: [AsyncFunction: getPieceMetadata],
    getPieceMetadataByKey: [AsyncFunction: getPieceMetadataByKey],
    getServicePrice: [AsyncFunction: getServicePrice],
    calculateStorageCost: [AsyncFunction: calculateStorageCost],
    checkAllowanceForStorage: [AsyncFunction: checkAllowanceForStorage],
    prepareStorageUpload: [AsyncFunction: prepareStorageUpload],
    terminateDataSet: [AsyncFunction: terminateDataSet],
    addApprovedProvider: [AsyncFunction: addApprovedProvider],
    removeApprovedProvider: [AsyncFunction: removeApprovedProvider],
    getApprovedProviderIds: [AsyncFunction: getApprovedProviderIds],
    isProviderIdApproved: [AsyncFunction: isProviderIdApproved],
    getOwner: [AsyncFunction: getOwner],
    isOwner: [AsyncFunction: isOwner],
    getMaxProvingPeriod: [AsyncFunction: getMaxProvingPeriod],
    getChallengeWindow: [AsyncFunction: getChallengeWindow],
    topUpCDNPaymentRails: [AsyncFunction: topUpCDNPaymentRails],
	,
  _warmStorageAddress: "0x02925630df557F957f70E112bA06e50965417CA0",
  _withCDN: true,
  _signer: NonceManager
	provider: WebSocketProvider;
	websocket: [Getter], _write;
	: [AsyncFunction: _write],
      destroy: [AsyncFunction: destroy],
      _getSubscriber: [Function: _getSubscriber],
      _register: [Function: _register],
      _send: [AsyncFunction: _send],
      _processMessage: [AsyncFunction: _processMessage],
      _getOption: [Function: _getOption],
      _network: [Getter],
      _perform: [AsyncFunction: _perform],
      _detectNetwork: [AsyncFunction: _detectNetwork],
      _start: [Function: _start],
      _waitUntilReady: [AsyncFunction: _waitUntilReady],
      ready: [Getter],
      getRpcTransaction: [Function: getRpcTransaction],
      getRpcRequest: [Function: getRpcRequest],
      getRpcError: [Function: getRpcError],
      send: [Function: send],
      getSigner: [AsyncFunction: getSigner],
      listAccounts: [AsyncFunction: listAccounts],
      pollingInterval: [Getter],
      provider: [Getter],
      plugins: [Getter],
      attachPlugin: [Function: attachPlugin],
      getPlugin: [Function: getPlugin],
      disableCcipRead: [Getter/Setter],
      ccipReadFetch: [AsyncFunction: ccipReadFetch],
      _wrapBlock: [Function: _wrapBlock],
      _wrapLog: [Function: _wrapLog],
      _wrapTransactionReceipt: [Function: _wrapTransactionReceipt],
      _wrapTransactionResponse: [Function: _wrapTransactionResponse],
      getBlockNumber: [AsyncFunction: getBlockNumber],
      _getAddress: [Function: _getAddress],
      _getBlockTag: [Function: _getBlockTag],
      _getFilter: [Function: _getFilter],
      _getTransactionRequest: [Function: _getTransactionRequest],
      getNetwork: [AsyncFunction: getNetwork],
      getFeeData: [AsyncFunction: getFeeData],
      estimateGas: [AsyncFunction: estimateGas],
      call: [AsyncFunction: call],
      getBalance: [AsyncFunction: getBalance],
      getTransactionCount: [AsyncFunction: getTransactionCount],
      getCode: [AsyncFunction: getCode],
      getStorage: [AsyncFunction: getStorage],
      broadcastTransaction: [AsyncFunction: broadcastTransaction],
      getBlock: [AsyncFunction: getBlock],
      getTransaction: [AsyncFunction: getTransaction],
      getTransactionReceipt: [AsyncFunction: getTransactionReceipt],
      getTransactionResult: [AsyncFunction: getTransactionResult],
      getLogs: [AsyncFunction: getLogs],
      _getProvider: [Function: _getProvider],
      getResolver: [AsyncFunction: getResolver],
      getAvatar: [AsyncFunction: getAvatar],
      resolveName: [AsyncFunction: resolveName],
      lookupAddress: [AsyncFunction: lookupAddress],
      waitForTransaction: [AsyncFunction: waitForTransaction],
      waitForBlock: [AsyncFunction: waitForBlock],
      _clearTimeout: [Function: _clearTimeout],
      _setTimeout: [Function: _setTimeout],
      _forEachSubscriber: [Function: _forEachSubscriber],
      _recoverSubscriber: [Function: _recoverSubscriber],
      on: [AsyncFunction: on],
      once: [AsyncFunction: once],
      emit: [AsyncFunction: emit],
      listenerCount: [AsyncFunction: listenerCount],
      listeners: [AsyncFunction: listeners],
      off: [AsyncFunction: off],
      removeAllListeners: [AsyncFunction: removeAllListeners],
      addListener: [AsyncFunction: addListener],
      removeListener: [AsyncFunction: removeListener],
      destroyed: [Getter],
      paused: [Getter/Setter],
      pause: [Function: pause],
      resume: [Function: resume],
	,
    signer: Wallet
	provider: [Object ...],
      address
	: "0xcd4E9682172f67f2eA8cf0a9eCF199F3b78e57aD",
      connect: [Function: connect],
      encrypt: [AsyncFunction: encrypt],
      encryptSync: [Function: encryptSync],
      signingKey: [Getter],
      privateKey: [Getter],
      getAddress: [AsyncFunction: getAddress],
      signTransaction: [AsyncFunction: signTransaction],
      signMessage: [AsyncFunction: signMessage],
      signMessageSync: [Function: signMessageSync],
      authorizeSync: [Function: authorizeSync],
      authorize: [AsyncFunction: authorize],
      signTypedData: [AsyncFunction: signTypedData],
      getNonce: [AsyncFunction: getNonce],
      populateCall: [AsyncFunction: populateCall],
      populateTransaction: [AsyncFunction: populateTransaction],
      populateAuthorization: [AsyncFunction: populateAuthorization],
      estimateGas: [AsyncFunction: estimateGas],
      call: [AsyncFunction: call],
      resolveName: [AsyncFunction: resolveName],
      sendTransaction: [AsyncFunction: sendTransaction],
	,
    getAddress: [AsyncFunction: getAddress],
    connect: [Function: connect],
    getNonce: [AsyncFunction: getNonce],
    increment: [Function: increment],
    reset: [Function: reset],
    sendTransaction: [AsyncFunction: sendTransaction],
    signTransaction: [Function: signTransaction],
    signMessage: [Function: signMessage],
    signTypedData: [Function: signTypedData],
    populateCall: [AsyncFunction: populateCall],
    populateTransaction: [AsyncFunction: populateTransaction],
    populateAuthorization: [AsyncFunction: populateAuthorization],
    estimateGas: [AsyncFunction: estimateGas],
    call: [AsyncFunction: call],
    resolveName: [AsyncFunction: resolveName],
    authorize: [Function: authorize],
	,
  _uploadBatchSize: 32,
  _dataSetId: undefined,
  _dataSetMetadata:
	filosign_user: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8", withCDN;
	: "",
	,
  _pendingPieces: [],
  _isProcessing: false,
  _activeUploads: Set
	,
  _uploadBatchWaitTimeout: 15000,
  serviceProvider: "0xB709A785c765d7d3F7d94dbA367DA6a611D7972b",
  withCDN: [Getter],
  provider: [Getter],
  dataSetMetadata: [Getter],
  dataSetId: [Getter],
  preflightUpload: [AsyncFunction: preflightUpload],
  upload: [AsyncFunction: upload],
  _processPendingPieces: [AsyncFunction: _processPendingPieces],
  download: [AsyncFunction: download],
  providerDownload: [AsyncFunction: providerDownload],
  getProviderInfo: [AsyncFunction: getProviderInfo],
  getDataSetPieces: [AsyncFunction: getDataSetPieces],
  getPieces: [AsyncGeneratorFunction: getPieces],
  _getPieceIdByCID: [AsyncFunction: _getPieceIdByCID],
  deletePiece: [AsyncFunction: deletePiece],
  hasPiece: [AsyncFunction: hasPiece],
  pieceStatus: [AsyncFunction: pieceStatus],
  terminate: [AsyncFunction: terminate],
}
